name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: push
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: run the code
        run: mkdir file1 .
