name: Push File

on: push

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: google-github-actions/setup-gcloud@v0
      
    - name: Pushes test file
      uses: chethanpichi/usb_fraud@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
